name: Build & Deploy MkDocs

on:
  push:
    branches: [ "main" ]

permissions:        # ← add this block (1-2 lines)
  contents: write   # allow push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs-material mkdocs-mermaid2-plugin
      - run: mkdocs gh-deploy --force --clean
